### ISSUE TITLE
Blackdog script permission issue

### ISSUE THREAD

**Issue by budioktaviyan** [azhsetiawan/ledzeplin#1] opened 2020-10-02 04:34 UTC
Zsh completion show unknown log while typing any command:
`osascript: couldn't save changes to script /usr/local/bin/blackdog.scpt: file is locked`

**Comment by azhsetiawan** [comment] 2020-10-02 05:42
I think that log was caused by permission. 
I'm assign to you, feel free to PR.

**Closed as completed** 2020-10-02 06:03 UTC
Labels: enhancement, hacktoberfest
